const CONSTANTS = {
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART' as const,
  LOAD_PRODUCTS_FROM_API: 'LOAD_PRODUCTS_FROM_API' as const,
  FILTER_PRODUCTS: 'FILTER_PRODUCTS' as const,
};

export default CONSTANTS;